### PR TITLE
Implements call to readability API through server

### PR DESCRIPTION
**Pull request by ChadFong**
addDocumentView.js:
- add ajax POST request to server at '/addDoc' with url
- has doc.save({}) awaiting further database implementation

server-config.js:
- adds endpoint for '/addDoc'

request-handler.js:
- adds readabilityRequest: makes request to readability API

### CODE REVIEW

**Comment by MichaelRoberts214** [comment]
This looks good. I'll merge it later unless anyone has any qualms.

**Comment by david-hammer** [comment]
the server-side stuff looks great!

i'm worried about the client-side changes conflicting with my recent refactor.

**Comment by david-hammer** [comment]
also -- i doubt this matters much in this case -- but we shouldn't post API keys to github

**Comment by ChadFong** [comment]
I can remove those if you'd like.
And my change to client side was minor, I can figure it out pretty quick

**Pull request closed without merging**
